language: node_js
node_js:
  - "8"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
install:
  - npm install
  - npm install canvas
script:
  - npm run build
  - npm run lint
  - npm run test-all
  - npm run coveralls
